spring:
  application:
    name: hello-kafka-service
  cloud:
    stream:
      defaultBinder: kafka
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input-in-0:
          destination: hello-topic
        output-out-0:
          destination: hello-topic

server:
  port: 8081
